### ISSUE TITLE
Clarify pricing

### ISSUE THREAD

**Issue by BSPlatt** [awsdocs/amazon-translate-developer-guide#16]
From: [Supported languages and language codes](https://github.com/awsdocs/amazon-translate-developer-guide/blob/master/doc_source/what-is-languages.md)  
`Amazon Translate does not charge you for translations in which the source language and target language are the same.`

It is not clear whether or not this includes the case where "auto" is supplied as the source language. Please update the page to include clarification.

**Comment by devlinbd2** [comment]
Thank you for raising this issue. I have clarified the note to include a sentence about auto.
