### ISSUE TITLE
Translations for docs (question)

### ISSUE THREAD

**Issue by vacilagodzila** [awsdocs/amazon-translate-developer-guide#2]
Hello, is the repo currently looking for spanish translations? I could fork, make a folder, and PR it, if so.

**Comment by cbigham** [comment]
Hi,
The repo is just the English language source for the Translate documentation. We translate it to Spanish, as well as six other languages. You can see the Spanish translation here: https://docs.aws.amazon.com/es_es/translate/latest/dg/what-is.html

Thanks for reaching out to us with the offer,
Chuck Bigham
AWS Developer Documentation
