### ISSUE TITLE
Supported language codes

### ISSUE THREAD

**Issue by Kralizek** [awsdocs/amazon-translate-developer-guide#6]
Hey, I couldn't find anywhere in the documentation a table saying which are the accepted codes for each language nor if the values are taken from any ISO table.

It's easy to guess that one should use `sv` for Swedish and `it` for Italian but I've been trying for a while to guess what's the language code for any of the two Chinese languages.

**Comment by joneps** [comment]
Hello @Kralizek , 
Thank you for your feedback and apologies for the slow response. I've made it easier to find the language codes--they're now listed on the first page of the docs: https://github.com/awsdocs/amazon-translate-developer-guide/blob/master/doc_source/what-is.md
Best wishes,
Jonathan

**Comment by Kralizek** [comment]
No worries for the delay. Thanks for taking your time to improve the documentation.
